package com.less.zhiro.entity;

public class AddressSk {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_sk.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address_sk.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_sk.id
     *
     * @return the value of address_sk.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_sk.id
     *
     * @param id the value for address_sk.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address_sk.address
     *
     * @return the value of address_sk.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address_sk.address
     *
     * @param address the value for address_sk.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }
}