package com.less.zhiro.entity;

public class JurisdictionInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction_info.jurisdictionid
     *
     * @mbggenerated
     */
    private Integer jurisdictionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction_info.menuid
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction_info.auth
     *
     * @mbggenerated
     */
    private String auth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction_info.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction_info.parent
     *
     * @mbggenerated
     */
    private Integer parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction_info.jurisdictionid
     *
     * @return the value of jurisdiction_info.jurisdictionid
     *
     * @mbggenerated
     */
    public Integer getJurisdictionid() {
        return jurisdictionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction_info.jurisdictionid
     *
     * @param jurisdictionid the value for jurisdiction_info.jurisdictionid
     *
     * @mbggenerated
     */
    public void setJurisdictionid(Integer jurisdictionid) {
        this.jurisdictionid = jurisdictionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction_info.menuid
     *
     * @return the value of jurisdiction_info.menuid
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction_info.menuid
     *
     * @param menuid the value for jurisdiction_info.menuid
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction_info.auth
     *
     * @return the value of jurisdiction_info.auth
     *
     * @mbggenerated
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction_info.auth
     *
     * @param auth the value for jurisdiction_info.auth
     *
     * @mbggenerated
     */
    public void setAuth(String auth) {
        this.auth = auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction_info.comment
     *
     * @return the value of jurisdiction_info.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction_info.comment
     *
     * @param comment the value for jurisdiction_info.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction_info.parent
     *
     * @return the value of jurisdiction_info.parent
     *
     * @mbggenerated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction_info.parent
     *
     * @param parent the value for jurisdiction_info.parent
     *
     * @mbggenerated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }
}