package com.less.zhiro.entity;

import java.util.Date;

public class RoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.createdatetime
     *
     * @mbggenerated
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.delflage
     *
     * @mbggenerated
     */
    private Integer delflage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.roleid
     *
     * @return the value of role_info.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.roleid
     *
     * @param roleid the value for role_info.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role
     *
     * @return the value of role_info.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role
     *
     * @param role the value for role_info.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.createdatetime
     *
     * @return the value of role_info.createdatetime
     *
     * @mbggenerated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.createdatetime
     *
     * @param createdatetime the value for role_info.createdatetime
     *
     * @mbggenerated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.delflage
     *
     * @return the value of role_info.delflage
     *
     * @mbggenerated
     */
    public Integer getDelflage() {
        return delflage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.delflage
     *
     * @param delflage the value for role_info.delflage
     *
     * @mbggenerated
     */
    public void setDelflage(Integer delflage) {
        this.delflage = delflage;
    }
}