package com.less.zhiro.entity;

import java.util.Date;

public class RoleJurisdiction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_jurisdiction.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_jurisdiction.roleid
     *
     * @mbggenerated
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_jurisdiction.jurisdictionid
     *
     * @mbggenerated
     */
    private Integer jurisdictionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_jurisdiction.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_jurisdiction.id
     *
     * @return the value of role_jurisdiction.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_jurisdiction.id
     *
     * @param id the value for role_jurisdiction.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_jurisdiction.roleid
     *
     * @return the value of role_jurisdiction.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_jurisdiction.roleid
     *
     * @param roleid the value for role_jurisdiction.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_jurisdiction.jurisdictionid
     *
     * @return the value of role_jurisdiction.jurisdictionid
     *
     * @mbggenerated
     */
    public Integer getJurisdictionid() {
        return jurisdictionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_jurisdiction.jurisdictionid
     *
     * @param jurisdictionid the value for role_jurisdiction.jurisdictionid
     *
     * @mbggenerated
     */
    public void setJurisdictionid(Integer jurisdictionid) {
        this.jurisdictionid = jurisdictionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_jurisdiction.createTime
     *
     * @return the value of role_jurisdiction.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_jurisdiction.createTime
     *
     * @param createtime the value for role_jurisdiction.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}