package com.less.zhiro.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.photoid
     *
     * @mbggenerated
     */
    private Integer photoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.createdatetime
     *
     * @mbggenerated
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.delflage
     *
     * @mbggenerated
     */
    private Integer delflage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.userid
     *
     * @return the value of user_info.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.userid
     *
     * @param userid the value for user_info.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.username
     *
     * @param username the value for user_info.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nickname
     *
     * @return the value of user_info.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nickname
     *
     * @param nickname the value for user_info.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @return the value of user_info.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @param phone the value for user_info.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.photoid
     *
     * @return the value of user_info.photoid
     *
     * @mbggenerated
     */
    public Integer getPhotoid() {
        return photoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.photoid
     *
     * @param photoid the value for user_info.photoid
     *
     * @mbggenerated
     */
    public void setPhotoid(Integer photoid) {
        this.photoid = photoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.createdatetime
     *
     * @return the value of user_info.createdatetime
     *
     * @mbggenerated
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.createdatetime
     *
     * @param createdatetime the value for user_info.createdatetime
     *
     * @mbggenerated
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.delflage
     *
     * @return the value of user_info.delflage
     *
     * @mbggenerated
     */
    public Integer getDelflage() {
        return delflage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.delflage
     *
     * @param delflage the value for user_info.delflage
     *
     * @mbggenerated
     */
    public void setDelflage(Integer delflage) {
        this.delflage = delflage;
    }
}