package com.less.zhiro.dao;

import com.less.zhiro.entity.AddressSk;
import java.util.List;

public interface AddressSkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_sk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_sk
     *
     * @mbggenerated
     */
    int insert(AddressSk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_sk
     *
     * @mbggenerated
     */
    AddressSk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_sk
     *
     * @mbggenerated
     */
    List<AddressSk> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address_sk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AddressSk record);
}