package com.less.zhiro.dao;

import com.less.zhiro.entity.RoleJurisdiction;
import java.util.List;

public interface RoleJurisdictionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_jurisdiction
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_jurisdiction
     *
     * @mbggenerated
     */
    int insert(RoleJurisdiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_jurisdiction
     *
     * @mbggenerated
     */
    RoleJurisdiction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_jurisdiction
     *
     * @mbggenerated
     */
    List<RoleJurisdiction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_jurisdiction
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleJurisdiction record);
}